---
- name: install required packages
  apt:
    name: '{{ item }}'
  with_items:
    - curl
    - apt-transport-https
    - lsb-release

- name: add key
  apt_key:
    url: http://packages.wazuh.com/key/GPG-KEY-WAZUH

- name: add repo
  apt_repository:
    repo: deb https://packages.wazuh.com/3.x/apt/ stable main

  # installing specific version via ansible apt module not working for ansible 2.2
- name: install wazuh-manager
  shell: |
    apt-get update
    apt-get install -y wazuh-manager="{{apt_ossec_version}}"
