---
- name: remove ossec-wazuh opt folder if exists
  file:
    path=/opt/ossec-wazuh
    state=absent

- name: get ossec-wazuh package
  get_url: url="{{ ossec_url }}/v{{ ossec_version }}.tar.gz" dest=/opt/ossec-wazuh.tar.gz

- name: unarchive ossec-wazuh package
  unarchive: src=/opt/ossec-wazuh.tar.gz dest=/opt/

  # Wazuh hardcoded version into folder name
- name: move directory
  command: mv /opt/wazuh-"{{ossec_version}}" /opt/ossec-wazuh

- name: copy preloaded var file
  template:
    src=install-preloaded-vars.conf
    dest=/opt/ossec-wazuh/etc/preloaded-vars.conf

- name: install ossec-wazuh
  shell: cd /opt/ossec-wazuh && ./install.sh