---
- name: install required packages
  apt:
    name: '{{ item }}'
  with_items:
    - curl
    - apt-transport-https
    - lsb-release

- name: add key
  apt_key:
    url: http://packages.wazuh.com/key/GPG-KEY-WAZUH

- name: add repo
  apt_repository:
    repo: deb https://packages.wazuh.com/3.x/apt/ stable main

- name: install wazuh-manager
  apt:
    name: wazuh-manager
    update_cache: yes
