---

- include: install-deb-package.yml
  when: not ossec_install_from_sources

- include: install-from-sources.yml
  when: ossec_install_from_sources


- name: Generate self-signed cert
  command: openssl req -new -newkey rsa:4096 -days 10000 -nodes -subj "/" -x509 -keyout /var/ossec/etc/sslmanager.key -out /var/ossec/etc/sslmanager.cert

# ossec-remoted won't run unless there's a record for a client.
# We will add a record that allows connections from 127.0.0.1
- name: Add keepalive client.keys
  copy:
    src=client.keys
    dest=/var/ossec/etc
    owner=root
    group=ossec
    mode=440

- name: copy ossec.conf
  template:
    src=ossec.conf
    dest=/var/ossec/etc/ossec.conf
    owner=root
    group=ossec

- name: enable auth
  shell: /var/ossec/bin/ossec-control enable auth
  notify:
    - restart wazuh-manager

- name: add update ruleset cronjob
  cron:
    name: OSSEC Ruleset Update
    job: cd /var/ossec/bin && ./update_ruleset.py -r
    special_time: "{{ ossec_ruleset_update_period }}"
  when: "{{ ossec_allow_ruleset_update }}"

# - name: check file
#   stat: path=/var/ossec/active-response/bin/ossec-slack.sh
#   register: ossec_slack_script
#   when: ossec_slack_enable_notifications

# - name: change SLACKUSER configuration
#   lineinfile:
#     destfile: /var/ossec/active-response/bin/ossec-slack.sh
#     regexp: '^SLACKUSER'
#     line: 'SLACKUSER="{{ossec_slack_user}}"'
#   when:
#     - ossec_slack_enable_notifications
#     - ossec_slack_script.stat.exists == True

# - name: change CHANNEL configuration
#   lineinfile:
#     destfile: /var/ossec/active-response/bin/ossec-slack.sh
#     regexp: '^CHANNEL'
#     line: 'CHANNEL="{{ossec_slack_channel}}"'
#   when:
#     - ossec_slack_enable_notifications
#     - ossec_slack_script.stat.exists == True

# - name: change SITE configuration
#   lineinfile:
#     destfile: /var/ossec/active-response/bin/ossec-slack.sh
#     regexp: '^SITE'
#     line: 'SITE="{{ossec_slack_webhook}}"'
#   when:
#     - ossec_slack_enable_notifications
#     - ossec_slack_script.stat.exists == True
